name: Deploy Snake to GitHub

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12h
  workflow_dispatch:       # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ðŸ”‘ PermissÃ£o para dar push no repositÃ³rio

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Snake to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output   # branch onde ficarÃ¡ o site
          build_dir: dist         # ðŸ‘ˆ pasta dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
